### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by waahm7** [waahm7/team-42-codeu#38]
We need to create a page where users can login into our website and can be navigated to dashboard on successful login.

**Comment by azanbinzahid** [comment]
1. I have added nice-looking login-page. On dev server, it will show the same old redirect page to login but on live-server, the login will be made through Google.
2. Currently, we are only using login through Google. If we want to login via manual email and password then we'll have to add a whole new layer and authentication system for login which is not suitable atm. 
3. On live-server, when the button redirects the call to Google for login, its the default Google login interface for java and we cannot alter its design.
4. To study more about how our login is working with Google, read more at https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/users/UserService

**Comment by azanbinzahid** [comment]
![Screenshot (220)](https://user-images.githubusercontent.com/47540683/59428802-c1d65b00-8df7-11e9-8f81-aaa6918db009.png)
![Screenshot (221)](https://user-images.githubusercontent.com/47540683/59428824-d0247700-8df7-11e9-9ec8-da5d4d3a8bfb.png)
