### ISSUE TITLE
Dashboard v2

### ISSUE THREAD

**Issue by waahm7** [waahm7/team-42-codeu#60]
Currently dashboard is working but it needs some improvements. I think it should at least these improvements. Feel free to do whatever you like.
- Make it permanently visible
- It should have sections (Active, recurring, archieved)
- It should load all opportunites from database in proper section
- It should display the selected opportunity in proper format (without any horizontal scroll bar)

**Comment by azanbinzahid** [comment]
ack()

**Comment by azanbinzahid** [comment]
Please list/review all PRs that are needed to merge before working on this.
